name: cbet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - torchaudio=0.10
  - torchvision=0.11
  - pytorch=1.10
  - polymetis=1077_g4d7b600e=py38_1077
  - cudatoolkit=11.3
  - umap-learn=0.5
  - scikit-learn=1.0.1
  - holoviews=1.14
  - bokeh=2.4.2
  - datashader=0.13
  - seaborn=0.11
  - ipykernel=6.9
  - jupyterlab=3.2
  - pip==22.0.3
  - mpi4py==3.1.3
  - gin-config==0.5.0
  - pip:
      - black==22.3.0
      - dm-control==0.0.403778684
      - einops==0.3.2
      - gym==0.21.0
      - hydra-core==1.2.0
      - ipdb==0.13.9
      - imageio==2.13.3
      - wandb==0.13.4
      - carla==0.9.13
      - shapely==1.8.1.post1
      - networkx==2.8
      - av==9.2.0
      - pybullet==3.2.1
      - protobuf==3.20.1
      - openvr==1.16.802
      - opencv-python==4.6.0.66
      - opencv-contrib-python==4.6.0.66
      - pyrealsense2==2.50.0.3812
      - pyzmq==23.1.0
      - futures==3.0.5
      - transformers==4.17.0
      - gdown==4.5.1
      - prettytable==3.3.0
      - bezier==2021.2.12
      - pynvml==11.4.1