defaults:
  - _self_
  - encoder: identity
  - action_ae: discretizers/k_means_kitchen_best
  - env: relay_kitchen_traj
  - state_prior: mingpt_kitchen_future_cond_best
  - env_vars: env_vars

lazy_init_models: False
# Dataset details
train_fraction: 0.95
batch_size: 64
num_workers: 16
window_size: 10
goal_conditional: future
goal_seq_len: 10

# Training details
num_training_epochs: 1
data_parallel: False
device: cuda:0
optim: Adam
save_latents: False

lr: 1e-4
weight_decay: 0
betas:
  - 0.9
  - 0.999
grad_norm_clip: 1.0
seed: 42

# Prior training details
num_prior_epochs: 50
train_encoder_with_prior: False
eval_prior_every: 1
save_prior_every: 1

# Logging frequency
eval_every: 1
save_every: 1

# Wandb config
project: cbet_repro_test
experiment: kitchen_train

hydra:
  job:
    override_dirname: ${experiment}
    chdir: True
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/sweep_${now:%H%M%S}_${experiment}
    subdir: ${hydra.job.num}
