_target_: models.latent_generators.mingpt.MinGPT

discrete_input: false
input_dim: ${encoder.output_dim}

vocab_size: ??? # TBD by the discretization model.

# Architecture details
n_layer: 4
n_head: 4
n_embd: 72
n_embd_is_per_head: False

block_size: ${window_size} # Length of history/context
predict_offsets: True
offset_loss_scale: 100000.0
focal_loss_gamma: 2.0
action_dim: ${env.action_dim}
goal_conditional: prepend
goal_dim: ${env.goal_dim}
goal_seq_len: ${goal_seq_len}
